markdown: kramdown
highlighter: rouge

permalink: pretty

title: Wyrd
tagline: 'Me finding my place in the world'
description: 'A blog about something and nothing. Meaning an exploration of what it means for me to exist.'


url: http://darthcoder.github.io
baseurl: /
 
author:
  name:           'Mark Otto'
  url:            https://twitter.com/basyt

paginate: 5

version: 0.1
