markdown: kramdown
highlighter: rouge

permalink: pretty

title: Asymmetrical Thoughts
tagline: "Imagining an Alternative Life"
description: "It is possible."
url: http://darthcoder.github.io
baseurl: /
 
author:
  name:           "Abdul Basit Ahmad"
  url:            https://github.com/darthcoder

paginate: 10

version: 0.20
