markdown: kramdown
highlighter: rouge

permalink: pretty

title: Evil(er)
tagline: "Nice Guy No More"
description: "I have spent three decades trying to fit in but I'm tired of playing catch up. Its time for a re-invention and a promise 
- I am not going to be a sucker ever again in my life. Period."


url: http://darthcoder.github.io
baseurl: /
 
author:
  name:           "Abdul Basit Ahmad"
  url:            https://github.com/darthcoder

paginate: 10

version: 0.20
