markdown: kramdown
highlighter: rouge

permalink: pretty

title: Asymmetrical Thoughts
tagline: "A blog about software development, programming, and technology."
description: "A blog about software development, programming, and technology."

url: http://darthcoder.github.io
baseurl: /
 
author:
  name:           "Abdul Basit Ahmad"
  url:            https://github.com/darthcoder

paginate: 10

version: 0.20
