markdown: redcarpet
highlighter: pygments

permalink: pretty

title: Asymmetrical Thoughts
tagline: 'Me finding my place in the world'
description: 'A blog about something and nothing. Meaning an exploration of what it means for me to exist'

author: 'Abdul Basit Ahmad'
paginate: 5

version: 0.1